### PR TITLE
Added release script

### LINKED ISSUE #59: Document/automate release process
Now that multiple people can publish to `npm`, we should have a consistent release process. We are pretty good with respect to `git tag` and `npm publish` but have missed a few `CHANGELOG.md` updates.

@wlaurance What's the current process that you follow?

### PR DESCRIPTION
**Pull request by twolfson**
In #59, we discussed the current steps taken to perform a release. This PR automates those steps to guarantee consistent releases across contributors. In this PR:

- Added `github-changes`
- Added `release.sh`, which leverages the steps discussed in #59 
- Updated `CHANGELOG.md` to match current release information
- Closes #59 

/cc @wlaurance

### CODE REVIEW

**Comment by twolfson** [comment]
It should be noted that I haven't run all of these steps (i.e. `npm version`, `git add/commit/push`, `npm publish`) but am very confident they should work or only have minor typos.

**Comment by wlaurance** [comment]
Just gave it a shot and released 1.5.1 with the new script!

**Comment by twolfson** [comment]
Woo hoo!

**Comment by twolfson** [comment]
It looks like the release broke the lint for requiring a trailing newline though =/

Maybe we need to add an `echo` after the `github-changes` invocation:

```bash
github-changes
# DEV: Add trailing newline for linter
echo >> CHANGELOG.md
```

**Comment by wlaurance** [comment]
It worked well, but it looks like it removed the new line from `CHANGELOG.md` which caused a build failure.

**Comment by wlaurance** [comment]
Ahh OK you saw it too.

Yeah, I'll try that.

**Pull request merged**
