### PR TITLE
close to tray

### PR DESCRIPTION
**Pull request by LuckyThirteen**
Just some small changes for better user experience (imo): 
  * clicking on the tray icon shows/hides the window instead of minimizing it (as a bonus this way the window size/position is preserved)
  * calling the executable should make the window visble in any case

### CODE REVIEW

**Comment by twolfson** [comment]
Typically this is a configuration option since different users prefer different behaviors. We should probably add some sort of pop-up to make this a toggle-able settings.

@wlaurance Thoughts on how we should handle settings like this?

**Comment by twolfson** [comment]
I was thinking that for the interim, we could have it be a CLI setting. However, for the long term, we should have some GUI component.

**Comment by bonyiii** [comment]
:+1: I think this should be fine as default behaviour.

**Comment by wlaurance** [comment]
@LuckyThirteen 

I think this is definitely a user preference. I prefer to have the window remain in my list of windows. I can see why some want it to minimize to the tray instead.

@twolfson 

I think a CLI setting would do the trick. And eventually we can have stored preferences somewhere.

**Comment by twolfson** [comment]
@LuckyThirteen To reduce the friction in blocking this PR, I will open another PR that adds in the basics for CLI parsing by the end of this weekend. It should have a very similar process as `google-music-electron`:

https://github.com/twolfson/google-music-electron/blob/1.11.0/bin/google-music-electron.js#L7-L16

https://github.com/twolfson/google-music-electron/blob/1.11.0/lib/google-music-electron.js#L11-L23

**Comment by LuckyThirteen** [comment]
@twolfson : Okay, cool. I'm not very good with js in general, but I'll try to update the PR to use the CLI options after they are done. Thanks for considering the change :)

**Comment by twolfson** [comment]
@LuckyThirteen I have opened a PR to add CLI option support, #64. If you want, you can rebase on top of it and add a new option:

```js
// At parse time
program
  .version(pkg.version)
  .option('--close-to-tray')
  .parse(argv);

// In script
var isHidden = false;
function showWindow() {
  isHidden = false;
  win.show();
}
function hideWindow() {
  isHidden = true;
  win.hide();
}
function toggleWindow() {
  if (isHidden) {
    showWindow();
  } else {
    hideWindow();
  }
}
if (program.closeToTray) {
  win.on('close', hideWindow);
}

var tray = gui.Tray({
  click: toggleWindow
});
```

I am still not entirely sure of the difference between hide/minimize. From my perspective, minimize does preserve the window position/size.

**Comment by LuckyThirteen** [comment]
@twolfson : thanks for the heads up, I'll do the rebase when I have a little time.
About the difference: the biggest one I guess is about showing the window in the window list or not.
Minimize preserved the window size for me too when using it from the window list, but clicking on the tray icon always opened a specific sized window.

**Comment by twolfson** [comment]
Hmm, I was previously basing my comments on my past assumptions. I have played around with minimize/restore vs show/hide on my computer. It looks like Cinnamon doesn't restore the position/size correctly from minimize. However, Cinnamon has issues with `nw.js` (e.g. `show_taskbar`) in recent versions so I can't guarantee that.

My experience:

- On minimize:
    - `slack-for-linux` is visible in taskbar
    - Window disappears
- On restore:
    - Window appears
    - Scaled to 300x400 and placed at center of 2 displays
- On hide:
    - `slack-for-linux` is removed from taskbar
    - Window disappears
- On show:
    - Window appears
    - `slack-for-linux` reappears in taskbar with original dimensions/position

I think it would be nice to have `show`/`hide` as alternative options. However, making the "close" action also perform a show feels like a conflation of two separate concepts. Can we break these down into 2 separate PRs?

- `--minimize-to-tray`, which will use `show/hide` over `minimize/restore`
- `--close-to-tray`, inherits from `--minimize-to-tray` and upon "close" triggers a `hide` action instead

**Comment by LuckyThirteen** [comment]
I use Openbox, and the minimize/restore & the hide/show experience is the same as yours.
Sure, let's do it two PRs, makes sense.

**Comment by LuckyThirteen** [comment]
@twolfson : I created the PRs: #68 & #69 .

**Comment by twolfson** [comment]
Ah, k. I was expecting this PR to become #69. I will close this one since the other 2 supercede this one.

**Pull request closed without merging**
